sudo: false
dist: trusty
language: node_js
node_js:
  - 6

env:
  - TEST_SUITE=main
  - TEST_SUITE=tz TZ_LENGTH=2 TZ_INDEX=0
  - TEST_SUITE=tz TZ_LENGTH=2 TZ_INDEX=1

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master
    - v2
    - "/v\\d+\\.\\d+\\.\\d+([\\w-\\.]+)?/"

script:
  - yarn run test-travis

before_deploy:
  - ./scripts/writeVersion.js
  - ./scripts/updateFirebase.js

# TODO: 1. npm -> script
#       2. Write
#         ‚ü© cat ~/.npmrc
#         //registry.npmjs.org/:_authToken=$NPM_KEY
deploy:
  provider: npm
  email: kossnocorp@gmail.com
  api_key:
    secure: Hi4MUZhrvibLGzgvzf7usaWBKmQSfl0p8bQEb+qT0HyAe4zbF9T/vDrRDvF/BVao0/XHTUTG0Q/+TYntm0Q8SJeUagmhoxRmvYGQEcGVPtKzkfzIohiMRGUo5BxQpHGFGs4r6O77Bsgti4uoUziBU6Ldw2qSb9QUi5PX3VT06eY=
  on:
    tags: true

after_deploy:
  - yarn run release-tweet

cache:
  yarn: true
  directories:
    - node_modules

addons:
  sauce_connect: true
